"""WorkflowEvent — facts that already happened."""

from enum import Enum


class WorkflowEvent(str, Enum):
    STORY_IMPORTED = "story_imported"
    STORY_SYNCED = "story_synced"
    STORY_ANALYZED = "story_analyzed"
    TEST_CASES_GENERATED = "test_cases_generated"
    STORY_APPROVED = "story_approved"
    STORY_REJECTED = "story_rejected"
    BDD_GENERATED = "bdd_generated"
    AUTOMATION_GENERATED = "automation_generated"
    PULL_REQUEST_CREATED = "pull_request_created"
    EXECUTION_STARTED = "execution_started"
    EXECUTION_COMPLETED = "execution_completed"
    EXECUTION_FAILED = "execution_failed"
    FAILURE_ANALYZED = "failure_analyzed"
    BUG_CREATED = "bug_created"
    REPORT_PUBLISHED = "report_published"
    BUGS_FILED_AND_REPORT_PUBLISHED = "bugs_filed_and_report_published"
    CRITICAL_POLICY_BREACH = "critical_policy_breach"
    IMPORT_FAILED = "import_failed"
    ANALYSIS_FAILED = "analysis_failed"
    TEST_GEN_FAILED = "test_gen_failed"
    QA_REJECTED_TERMINAL = "qa_rejected_terminal"
    BDD_FAILED = "bdd_failed"
    AUTOMATION_FAILED = "automation_failed"
    PR_FAILED = "pr_failed"
    EXECUTION_FAILED_TO_START = "execution_failed_to_start"
    EXECUTION_ABORTED = "execution_aborted"
    WORKFLOW_FAILED = "workflow_failed"
    WORKFLOW_COMPLETED = "workflow_completed"
    WORKFLOW_CANCELLED = "workflow_cancelled"
